DEBUG = True

SECRET_KEY='No-so-secret-key'


MYSQL_DATABASE_HOST	= 'mysqldb'
MYSQL_DATABASE_PORT	= 3306
MYSQL_DATABASE_USER	= 'inscription'
MYSQL_DATABASE_PASSWORD	= 'root'
MYSQL_DATABASE_DB	= 'inscription'
MYSQL_DATABASE_CHARSET = 'utf-8'